class LocalColors {
  /// Skonfiguruj poniższy link. Dodaj do niego po prostu nazwę pliku z wylistowanych symboli np: TPU-CB01.webp
  /// Ustawiliśmy domyślną strukturę linku (możesz w każdej chwili podmienić 'colors' na nazwę swojego bucketu).
  static const String supabaseBucketBaseUrl = 'https://wljdozodcnzslcqbrpwu.supabase.co/storage/v1/object/public/public_assets/';

  static final List<Map<String, String?>> rawList = [
    {'symbol': 'TPU-CB01', 'hex': '#3f4444', 'name': 'Carbon Fiber'},
    {'symbol': 'TPU-CB22', 'hex': '#f2f3f0', 'name': 'Clear Carbon Fiber'},
    {'symbol': 'TPU-CB23', 'hex': '#dce1e0', 'name': 'Matte Clear Carbon Fiber'},
    {'symbol': 'TPU-CB24', 'hex': '#414248', 'name': 'Matt Carbon Fiber'},
    {'symbol': 'TPU-CB31', 'hex': '#afb4bb', 'name': 'Carbon Fiber Electric Silver'},
    {'symbol': 'TPU-D050', 'hex': '#495253', 'name': 'Diamond Aurora Green'},
    {'symbol': 'TPU-D070', 'hex': '#dcd6d1', 'name': 'Diamond White Blue'},
    {'symbol': 'TPU-D080', 'hex': '#e2dad4', 'name': 'Diamond White Pink'},
    {'symbol': 'TPU-D100', 'hex': '#f1f0ea', 'name': 'Diamond White Gold'},
    {'symbol': 'TPU-D210', 'hex': '#555f69', 'name': 'Diamond Aquamarine Black'},
    {'symbol': 'TPU-DM150', 'hex': '#232428', 'name': 'Matte Diamond Graphite Gray (BMW)'},
    {'symbol': 'TPU-DR080', 'hex': '#e7fdf6', 'name': 'Dreamlike Tiffany Pink'},
    {'symbol': 'TPU-DR090', 'hex': '#e6eae0', 'name': 'Dreamlike Turquoise Green'},
    {'symbol': 'TPU-DR100', 'hex': '#b2a5a5', 'name': 'Dream Phantom Volcano Gray'},
    {'symbol': 'TPU-DR110', 'hex': '#fdf0eb', 'name': 'Dream Gray Phantom Purple'},
    {'symbol': 'TPU-DR170', 'hex': '#fdf0eb', 'name': 'Dream Rouge Pink'},
    {'symbol': 'TPU-DR230', 'hex': '#c6b3b5', 'name': 'Starlight Gray Phantom'},
    {'symbol': 'TPU-DR250', 'hex': '#323138', 'name': 'Dreamy Streamer Black Charm Red'},
    {'symbol': 'TPU-DR270', 'hex': '#dcc4f5', 'name': 'Dreamlike Floating Purple'},
    {'symbol': 'TPU-FR020', 'hex': '#5aa9ae', 'name': 'Magic Splendid Green'},
    {'symbol': 'TPU-FR130', 'hex': '#6f9793', 'name': 'Magic Grass Green'},
    {'symbol': 'TPU-FR301', 'hex': '#62c1aa', 'name': 'Magic Ambilight'},
    {'symbol': 'TPU-FR307', 'hex': '#8c80bf', 'name': 'Magic Spectrum Purple'},
    {'symbol': 'TPU-FR308', 'hex': '#c4a6c0', 'name': 'Medium Gold Starry Sky Pink'},
    {'symbol': 'TPU-G010', 'hex': '#fd015f', 'name': 'Glossy Ferrari Red'},
    {'symbol': 'TPU-G014', 'hex': '#9e024d', 'name': 'Glossy Starlight Ruby Red'},
    {'symbol': 'TPU-G016', 'hex': '#fb6b8a', 'name': 'Glossy Strawberry Red (Porsche)'},
    {'symbol': 'TPU-G040', 'hex': '#fdefe6', 'name': 'Shell Pink'},
    {'symbol': 'TPU-G066', 'hex': '#dec09c', 'name': 'Glossy Sahara Yellow'},
    {'symbol': 'TPU-G071', 'hex': '#fee503', 'name': 'Glossy Signal Yellow (Porsche)'},
    {'symbol': 'TPU-G076', 'hex': '#fe6869', 'name': 'Glossy Lava Orange (Porsche)'},
    {'symbol': 'TPU-G077', 'hex': '#ffaf50', 'name': 'Glossy McLaren Orange'},
    {'symbol': 'TPU-G083', 'hex': '#e7fbe4', 'name': 'Glossy Dusty Green'},
    {'symbol': 'TPU-G088', 'hex': '#c4b99f', 'name': 'Glossy Armor Green'},
    {'symbol': 'TPU-G092', 'hex': '#8fea40', 'name': 'Glossy Viper Green (Audi)'},
    {'symbol': 'TPU-G094', 'hex': '#c8f8e6', 'name': 'Glossy Mint Green (Porsche)'},
    {'symbol': 'TPU-G095', 'hex': '#d5fcef', 'name': 'Glossy Tiffany'},
    {'symbol': 'TPU-G096', 'hex': '#edf7ef', 'name': 'Brilliant Rugged Green'},
    {'symbol': 'TPU-G110', 'hex': '#bfe4ee', 'name': 'Glossy Sky Blue'},
    {'symbol': 'TPU-G118', 'hex': '#84a8ba', 'name': 'Glossy Celadon Blue'},
    {'symbol': 'TPU-G126', 'hex': '#d0e7e6', 'name': 'Glossy Glacier Blue'},
    {'symbol': 'TPU-G128', 'hex': '#00b5d5', 'name': 'Glossy Miami Blue'},
    {'symbol': 'TPU-G129', 'hex': '#59728e', 'name': 'Glossy Neptune Blue (Porsche)'},
    {'symbol': 'TPU-G131', 'hex': '#c0f8f3', 'name': 'Glossy Turquoise Blue (Cullinan)'},
    {'symbol': 'TPU-G136', 'hex': '#2c4f63', 'name': 'Glossy Deep Blue (Porsche)'},
    {'symbol': 'TPU-G160', 'hex': '#212528', 'name': 'Glossy Piano Black'},
    {'symbol': 'TPU-G175', 'hex': '#665e57', 'name': 'Glossy Battleship Gray'},
    {'symbol': 'TPU-G181', 'hex': '#93847e', 'name': 'Glossy Cement Gray (Light)'},
    {'symbol': 'TPU-G182', 'hex': '#3b414a', 'name': 'Glossy Cement Gray (Blue)'},
    {'symbol': 'TPU-G188', 'hex': '#545356', 'name': 'Glossy Polar Gray'},
    {'symbol': 'TPU-G200', 'hex': '#e1dbd6', 'name': 'Elegant White'},
    {'symbol': 'TPU-G201', 'hex': '#dcd7cd', 'name': 'Brilliant Hanyu White'},
    {'symbol': 'TPU-G220', 'hex': '#dedcd8', 'name': 'Glossy Volcanic Gray'},
    {'symbol': 'TPU-G279', 'hex': '#bfd1d4', 'name': 'Glossy Meissen Blue'},
    {'symbol': 'TPU-G280', 'hex': '#0bbdac', 'name': 'Glossy Hell Green'},
    {'symbol': 'TPU-G339', 'hex': '#f2c56b', 'name': 'Glossy Combat Green (Rolls-Royce)'},
    {'symbol': 'TPU-G366', 'hex': '#fef9f6', 'name': 'Glossy Mary Kay Pink'},
    {'symbol': 'TPU-G370', 'hex': '#c7e1e6', 'name': 'Glossy Sea Breeze Blue'},
    {'symbol': 'TPU-G371', 'hex': '#d6beef', 'name': 'Glossy Lavender Purple'},
    {'symbol': 'TPU-G375', 'hex': '#fd5987', 'name': 'Glossy Beetroot Purple'},
    {'symbol': 'TPU-G377', 'hex': '#5b6770', 'name': 'Glossy Dark Emerald Green'},
    {'symbol': 'TPU-G411', 'hex': '#b38d7a', 'name': 'Glossy Mirror Pink'},
    {'symbol': 'TPU-G413', 'hex': '#b9803d', 'name': 'Glossy Desert Yellow (Mercedes-Benz)'},
    {'symbol': 'TPU-G416', 'hex': null, 'name': 'Glossy Mist Gray Purple'},
    {'symbol': 'TPU-G417', 'hex': '#b47379', 'name': 'Glossy Oolong Milk Tea Pink'},
    {'symbol': 'TPU-G418', 'hex': '#5f676d', 'name': 'Glossy Black Olive'},
    {'symbol': 'TPU-G421', 'hex': '#73696a', 'name': 'Brilliant Murky Camo (Porsche)'},
    {'symbol': 'TPU-G422', 'hex': '#c7a474', 'name': 'Glossy Cuban Sand'},
    {'symbol': 'TPU-G423', 'hex': '#9caaa7', 'name': 'Glossy Autumn Blue'},
    {'symbol': 'TPU-G424', 'hex': '#0178c8', 'name': 'Glossy Lugano Blue'},
    {'symbol': 'TPU-G425', 'hex': '#b96a74', 'name': 'Glossy Morganite Pink'},
    {'symbol': 'TPU-G426', 'hex': '#bdb0ab', 'name': 'Glossy Storm Gray'},
    {'symbol': 'TPU-G427', 'hex': '#d0e1eb', 'name': 'Glossy Zandvoort Blue'},
    {'symbol': 'TPU-G428', 'hex': '#d6cace', 'name': 'Glossy Mist Gray Purple (Deep)'},
    {'symbol': 'TPU-G429', 'hex': null, 'name': 'Glossy Elegant Gray'},
    {'symbol': 'TPU-G430', 'hex': '#82b989', 'name': 'Glossy Racing Green'},
    {'symbol': 'TPU-G431', 'hex': '#806361', 'name': 'Glossy Chocolate'},
    {'symbol': 'TPU-G432', 'hex': '#faf014', 'name': 'Glossy Modena Yellow'},
    {'symbol': 'TPU-G433', 'hex': '#5a524c', 'name': 'Glossy Arabian Gray'},
    {'symbol': 'TPU-G434', 'hex': '#ff6f80', 'name': 'Glossy Red'},
    {'symbol': 'TPU-G435', 'hex': '#8e9296', 'name': 'Glossy Rock Gray'},
    {'symbol': 'TPU-G436', 'hex': '#f4b19c', 'name': 'Glossy Coral Orange'},
    {'symbol': 'TPU-G437', 'hex': '#454f57', 'name': 'Glossy Sapphire Blue'},
    {'symbol': 'TPU-G501', 'hex': '#e0caab', 'name': 'Glossy Pepper White'},
    {'symbol': 'TPU-G503', 'hex': '#e59d5c', 'name': 'Glossy Desert Storm (Mercedes-Benz)'},
    {'symbol': 'TPU-G505', 'hex': '#a9c299', 'name': 'Glossy Brilliant Brilliant Green'},
    {'symbol': 'TPU-G506', 'hex': '#f9ff69', 'name': 'Glossy Acid Green'},
    {'symbol': 'TPU-G507', 'hex': '#4da494', 'name': 'Glossy Vintage Green'},
    {'symbol': 'TPU-G508', 'hex': '#c6beaa', 'name': 'Glossy Agate Gray'},
    {'symbol': 'TPU-G509', 'hex': '#908277', 'name': 'Glossy Gray (Light)'},
    {'symbol': 'TPU-G511', 'hex': '#c7bcd7', 'name': 'Glossy Manta Purple'},
    {'symbol': 'TPU-G513', 'hex': '#33d8de', 'name': 'Glossy Peacock Blue'},
    {'symbol': 'TPU-G611', 'hex': '#0bc5c9', 'name': 'Xiaomi Original Gulf Blue'},
    {'symbol': 'TPU-G613', 'hex': '#818ab0', 'name': 'Original Victoria\'s Secret Purple'},
    {'symbol': 'TPU-GM99', 'hex': '#191b1d', 'name': 'Matt Black'},
    {'symbol': 'TPU-M014', 'hex': '#8e7776', 'name': 'Metallic Rouge Pearl Pink'},
    {'symbol': 'TPU-M10', 'hex': '#c0c2c3', 'name': 'Metallic Silver'},
    {'symbol': 'TPU-M100', 'hex': '#313035', 'name': 'Metallic Graphite Gray (BMW)'},
    {'symbol': 'TPU-M104', 'hex': '#6391aa', 'name': 'Metallic Ice Blue (Porsche)'},
    {'symbol': 'TPU-M106', 'hex': '#a1a3a9', 'name': 'Metallic GT Silver (Porsche)'},
    {'symbol': 'TPU-M109', 'hex': '#5b4f63', 'name': 'Metallic Venetian Purple'},
    {'symbol': 'TPU-M111', 'hex': '#4a6199', 'name': 'Metallic Tanzanite Blue (BMW)'},
    {'symbol': 'TPU-M113', 'hex': '#2c2c2e', 'name': 'Metallic Tourmaline Gray'},
    {'symbol': 'TPU-M118', 'hex': '#98a49d', 'name': 'Metallic Aventurine Green'},
    {'symbol': 'TPU-M126', 'hex': '#e3f1ee', 'name': 'Metallic Glacier Blue'},
    {'symbol': 'TPU-M127', 'hex': null, 'name': 'Metallic Antarctic Blue'},
    {'symbol': 'TPU-M128', 'hex': '#fdfafe', 'name': 'Metallic Star Purple'},
    {'symbol': 'TPU-M13', 'hex': '#796c73', 'name': 'Metallic Ice Berry Pink'},
    {'symbol': 'TPU-M130', 'hex': '#48545e', 'name': 'Metallic Byron Bay Blue'},
    {'symbol': 'TPU-M131', 'hex': '#a8c5bb', 'name': 'Metallic Francis Green'},
    {'symbol': 'TPU-M133', 'hex': '#d2b296', 'name': 'Metallic Milan Gold (BMW)'},
    {'symbol': 'TPU-M136', 'hex': '#c3baad', 'name': 'Metallic Silver Fox Gray'},
    {'symbol': 'TPU-M143', 'hex': '#b2bcab', 'name': 'Metallic Alpine Green'},
    {'symbol': 'TPU-M144', 'hex': '#32383f', 'name': 'Metallic Coal Gray'},
    {'symbol': 'TPU-M145', 'hex': '#efedee', 'name': 'Metallic Aka Gold'},
    {'symbol': 'TPU-M147', 'hex': '#527b7b', 'name': 'Metallic Royal Green'},
    {'symbol': 'TPU-M148', 'hex': '#427e88', 'name': 'Metallic Qianshan Jade'},
    {'symbol': 'TPU-M150', 'hex': '#333e41', 'name': 'Metallic Eucalyptus Green'},
    {'symbol': 'TPU-M154', 'hex': '#908bb8', 'name': 'Metallic Gray Violet (Bentley)'},
    {'symbol': 'TPU-M155', 'hex': '#d3ddd8', 'name': 'Metallic Aurora Green (NIO)'},
    {'symbol': 'TPU-M161', 'hex': '#707865', 'name': 'Metallic Oak Green'},
    {'symbol': 'TPU-M162', 'hex': '#2b2f35', 'name': 'Metallic Black Jade'},
    {'symbol': 'TPU-M163', 'hex': '#cdccc8', 'name': 'Metallic Paint Sky Gray'},
    {'symbol': 'TPU-M164', 'hex': '#f7934c', 'name': 'Metallic Gold Madeira Gold'},
    {'symbol': 'TPU-M165', 'hex': '#286277', 'name': 'Metallic Montego Blue'},
    {'symbol': 'TPU-M166', 'hex': '#3f4f53', 'name': 'Metallic Goodwood Green'},
    {'symbol': 'TPU-M167', 'hex': '#aae0e7', 'name': 'Metallic Martin Racing Green'},
    {'symbol': 'TPU-M168', 'hex': '#fdb900', 'name': 'Metallic Paint Volcano Yellow'},
    {'symbol': 'TPU-M169', 'hex': '#0c50c1', 'name': 'Metallic Sapphire (Ferrari)'},
    {'symbol': 'TPU-M170', 'hex': '#3d2635', 'name': 'Metallic Amethyst (Ferrari)'},
    {'symbol': 'TPU-M171', 'hex': '#ff4971', 'name': 'Metallic Magic Flame Golden Red (Ferrari)'},
    {'symbol': 'TPU-M172', 'hex': '#707d90', 'name': 'Metallic Santorini Black (Land Rover)'},
    {'symbol': 'TPU-M173', 'hex': '#ebf4f3', 'name': 'Metallic Muriwai White'},
    {'symbol': 'TPU-M174', 'hex': '#292b31', 'name': 'Metallic Obsidian Black'},
    {'symbol': 'TPU-M175', 'hex': '#435258', 'name': 'Metallic Turquoise Green (Mercedes-Benz)'},
    {'symbol': 'TPU-M18', 'hex': '#505e7b', 'name': 'Metallic Navara Blue (Audi)'},
    {'symbol': 'TPU-M200', 'hex': '#999797', 'name': 'Liquid Metal Silver'},
    {'symbol': 'TPU-M201', 'hex': '#5e2630', 'name': 'Liquid Metal Dragon Blood Red'},
    {'symbol': 'TPU-M202', 'hex': '#454447', 'name': 'Liquid Metallic Gunmetal Gray'},
    {'symbol': 'TPU-M206', 'hex': '#1a638a', 'name': 'Liquid Metallic Interstellar Blue'},
    {'symbol': 'TPU-M207', 'hex': '#7e959f', 'name': 'Liquid Metallic Somato Blue'},
    {'symbol': 'TPU-M211', 'hex': '#a89bc1', 'name': 'Liquid Metallic Amber'},
    {'symbol': 'TPU-M212', 'hex': '#3b3b3d', 'name': 'Liquid Metallic Tungsten'},
    {'symbol': 'TPU-M215', 'hex': '#606b7e', 'name': 'Metallic Mercedes-Benz Charcoal Blue'},
    {'symbol': 'TPU-M216', 'hex': '#424a97', 'name': 'Metallic Royal Ingot Blue'},
    {'symbol': 'TPU-M217', 'hex': '#687a96', 'name': 'Metallic Mahogany Red'},
    {'symbol': 'TPU-M219', 'hex': '#c6a8bb', 'name': 'Metallic Passion Pink (Bentley)'},
    {'symbol': 'TPU-M221', 'hex': '#9bb2b3', 'name': 'Liquid Metallic Cangling Green'},
    {'symbol': 'TPU-M232', 'hex': '#837c78', 'name': 'Liquid Metallic Bronze'},
    {'symbol': 'TPU-M233', 'hex': '#f0efeb', 'name': 'Liquid Metallic Mousse White'},
    {'symbol': 'TPU-M234', 'hex': '#da3b5e', 'name': 'Liquid Metallic Cherry Red'},
    {'symbol': 'TPU-M235', 'hex': '#fff9f6', 'name': 'Liquid Metallic Shell Pink'},
    {'symbol': 'TPU-M237', 'hex': '#eceef0', 'name': 'Liquid Interstellar Silver'},
    {'symbol': 'TPU-M241', 'hex': '#4a5055', 'name': 'Liquid Metallic Dark Gray'},
    {'symbol': 'TPU-M243', 'hex': '#f0efeb', 'name': 'Liquid Metallic Crescent White'},
    {'symbol': 'TPU-M244', 'hex': '#ebedee', 'name': 'Liquid Metallic Titanium Silver'},
    {'symbol': 'TPU-M245', 'hex': '#474244', 'name': 'Liquid Metallic Titanium Gray'},
    {'symbol': 'TPU-M246', 'hex': '#d6dce1', 'name': 'Liquid Metallic Premium Gray'},
    {'symbol': 'TPU-M247', 'hex': '#e8d4d0', 'name': 'Liquid Metallic Dynamic Pink'},
    {'symbol': 'TPU-M248', 'hex': '#c3aecc', 'name': 'Liquid Metallic Jedi Pink'},
    {'symbol': 'TPU-M249', 'hex': '#aca7a0', 'name': 'Liquid Metallic Gatala Gray'},
    {'symbol': 'TPU-M250', 'hex': '#606871', 'name': 'Liquid Metallic Crescent Gray'},
    {'symbol': 'TPU-M251', 'hex': '#e9f3f2', 'name': 'Liquid Metallic Stratosphere Blue'},
    {'symbol': 'TPU-M252', 'hex': '#e0ebee', 'name': 'Liquid Metallic Monet Blue'},
    {'symbol': 'TPU-M253', 'hex': '#e6efee', 'name': 'Liquid Metallic Grace Green'},
    {'symbol': 'TPU-M254', 'hex': '#bdcfe0', 'name': 'Liquid Metallic Tungsten Blue'},
    {'symbol': 'TPU-M255', 'hex': '#372728', 'name': 'Liquid Metal Coffee'},
    {'symbol': 'TPU-M257', 'hex': '#e8eaee', 'name': 'Liquid Metallic Mercury'},
    {'symbol': 'TPU-M28', 'hex': '#37282f', 'name': 'Metallic Black Rose'},
    {'symbol': 'TPU-M322', 'hex': '#bfbbb5', 'name': 'Original Metallic Champagne Gold'},
    {'symbol': 'TPU-M323', 'hex': '#737e71', 'name': 'Aquila Metallic'},
    {'symbol': 'TPU-M324', 'hex': '#a9a4a5', 'name': 'Liquid Metal Aluminum Mercury'},
    {'symbol': 'TPU-M325', 'hex': '#757b82', 'name': 'Metallic Smooth Lime T'},
    {'symbol': 'TPU-M327', 'hex': '#00bbe2', 'name': 'Metallic Canel Bay Blue'},
    {'symbol': 'TPU-M338', 'hex': '#ffac98', 'name': 'Metallic Racing Orange'},
    {'symbol': 'TPU-M44', 'hex': '#90a28a', 'name': 'Metallic Mamba Green'},
    {'symbol': 'TPU-M50', 'hex': '#68626d', 'name': 'Metallic Midnight Red'},
    {'symbol': 'TPU-M51', 'hex': '#6d6c8a', 'name': 'Metallic Midnight Purple'},
    {'symbol': 'TPU-M527', 'hex': '#740c5d', 'name': 'Metallic Glazed Tata Red'},
    {'symbol': 'TPU-M528', 'hex': '#743c46', 'name': 'Metallic Crimson Tee'},
    {'symbol': 'TPU-M529', 'hex': '#6f62a6', 'name': 'Metallic Maverick Purple'},
    {'symbol': 'TPU-M530', 'hex': '#816ebb', 'name': 'Metallic GT Violet'},
    {'symbol': 'TPU-M531', 'hex': '#8165a5', 'name': 'Metallic Brilliant Black Purple'},
    {'symbol': 'TPU-M532', 'hex': '#e0e9e9', 'name': 'Metallic Hadrian Green'},
    {'symbol': 'TPU-M533', 'hex': '#424246', 'name': 'Metallic Bernina Gray'},
    {'symbol': 'TPU-M534', 'hex': '#616370', 'name': 'Metallic Black Cherry'},
    {'symbol': 'TPU-M535', 'hex': '#7a9490', 'name': 'Metallic Forest Green'},
    {'symbol': 'TPU-M536', 'hex': '#ac9b9f', 'name': 'Provence Purple'},
    {'symbol': 'TPU-M538', 'hex': '#b2a6b5', 'name': 'Metallic Sunshine Purple'},
    {'symbol': 'TPU-M544', 'hex': '#d0bbce', 'name': 'Metallic Amethyst'},
    {'symbol': 'TPU-M545', 'hex': '#524859', 'name': 'Metallic Dark Night Purple'},
    {'symbol': 'TPU-M546', 'hex': '#c1b9b2', 'name': 'Metallic Brooklyn Gray'},
    {'symbol': 'TPU-M547', 'hex': '#497478', 'name': 'Metallic Sand Green'},
    {'symbol': 'TPU-M548', 'hex': '#303238', 'name': 'Metallic Dark Night Red'},
    {'symbol': 'TPU-M549', 'hex': '#37272c', 'name': 'Metallic Brocade Red'},
    {'symbol': 'TPU-M550', 'hex': '#e8e1df', 'name': 'Metallic Champagne Gold'},
    {'symbol': 'TPU-M551', 'hex': '#776073', 'name': 'Metallic Leblon Purple'},
    {'symbol': 'TPU-M552', 'hex': '#767885', 'name': 'Metallic Galaxy Purple'},
    {'symbol': 'TPU-M553', 'hex': '#8ae2c9', 'name': 'Metallic Emerald Green'},
    {'symbol': 'TPU-M554', 'hex': '#ffb59e', 'name': 'Metallic Copper Brown'},
    {'symbol': 'TPU-M555', 'hex': '#ddeff0', 'name': 'Metallic Cold Crystal Light Cyan'},
    {'symbol': 'TPU-M556', 'hex': '#313538', 'name': 'Pearl Black'},
    {'symbol': 'TPU-M557', 'hex': '#cdc3e2', 'name': 'Metallic Spiritual Realm Purple'},
    {'symbol': 'TPU-M558', 'hex': '#fd7d64', 'name': 'Metallic Papaia Orange'},
    {'symbol': 'TPU-M559', 'hex': '#b5b9e3', 'name': 'Metallic Fantasy Rosemary Purple'},
    {'symbol': 'TPU-M560', 'hex': '#3c3036', 'name': 'Metallic Cuprite'},
    {'symbol': 'TPU-M59', 'hex': '#ff3879', 'name': 'Metallic Soul Red'},
    {'symbol': 'TPU-M61', 'hex': '#587373', 'name': 'Metallic Mercedes-Benz Emerald Green'},
    {'symbol': 'TPU-M616', 'hex': '#a2abb1', 'name': 'Metallic Shark Blue'},
    {'symbol': 'TPU-M617', 'hex': '#1685cf', 'name': 'Metallic Blue'},
    {'symbol': 'TPU-M618', 'hex': '#044876', 'name': 'Metallic Diamond Blue'},
    {'symbol': 'TPU-M619', 'hex': '#879daf', 'name': 'Metallic Glacier Blue Tee'},
    {'symbol': 'TPU-M620', 'hex': '#56254c', 'name': 'Metallic Twilight Rose'},
    {'symbol': 'TPU-M63', 'hex': '#768f75', 'name': 'Metallic Sonoma Green'},
    {'symbol': 'TPU-M66', 'hex': '#4f727d', 'name': 'Metallic British Green'},
    {'symbol': 'TPU-M75', 'hex': '#9c8596', 'name': 'Metallic Crystal Bronze'},
    {'symbol': 'TPU-M79', 'hex': '#f6f3f7', 'name': 'Metallic Silver Phantom Purple'},
    {'symbol': 'TPU-M80', 'hex': '#d3e1ef', 'name': 'Metallic Mist Blue'},
    {'symbol': 'TPU-M901', 'hex': '#5b5f64', 'name': 'Metallic Tungsten Steel'},
    {'symbol': 'TPU-M94', 'hex': '#515f68', 'name': 'Metallic Moonlight Gray'},
    {'symbol': 'TPU-M99', 'hex': '#353c3e', 'name': 'Metallic Black'},
    {'symbol': 'TPU-MG05', 'hex': '#ddd7d3', 'name': 'Fantasy Dawn White'},
    {'symbol': 'TPU-MG33', 'hex': '#ffb296', 'name': 'Fantasy Golden Orange'},
    {'symbol': 'TPU-MG36', 'hex': '#dafddd', 'name': 'Illusionary Gold Green'},
    {'symbol': 'TPU-MG77', 'hex': '#dff098', 'name': 'Fantasy Fluorescent Yellow'},
    {'symbol': 'TPU-PM150', 'hex': '#1c1b20', 'name': 'Electric Metallic Black'},
    {'symbol': 'TPU-PM160', 'hex': '#3e3f48', 'name': 'Electric Metallic Space Gray'},
    {'symbol': 'TPU-PM190', 'hex': '#b9bbbc', 'name': 'Electric Titanium Silver'},
    {'symbol': 'TPU-PM200', 'hex': '#ddd9d4', 'name': 'Electric Metallic White'},
    {'symbol': 'TPU-PM90', 'hex': '#969696', 'name': 'Electric Titanium Gray'},
    {'symbol': 'TPU-PR00', 'hex': '#c8c2be', 'name': 'Laser White'},
    {'symbol': 'TPU-PR11', 'hex': '#faf4f2', 'name': 'Laser Rouge Pink'},
    {'symbol': 'TPU-PR99', 'hex': '#282a2e', 'name': 'Laser Black'},
    {'symbol': 'TPU-R61', 'hex': '#a1ab8c', 'name': 'Rainbow Emerald Green'},
    {'symbol': 'TPU-R90', 'hex': '#454850', 'name': 'Magic Flame Splendid Gray'},
    {'symbol': 'TPU-SC99', 'hex': '#1c1d21', 'name': 'Ceramic Black'},
    {'symbol': 'TPU-SM100', 'hex': '#b5aeac', 'name': 'Super Matte Aluminum Mercury'},
    {'symbol': 'TPU-SM102', 'hex': '#55a8a0', 'name': 'Super Matte Satin Racing Green'},
    {'symbol': 'TPU-SM118', 'hex': '#006e9d', 'name': 'Super Magic Flame Dark Night Blue'},
    {'symbol': 'TPU-SM15', 'hex': '#a5b7c5', 'name': 'Super Matte Fantasy Gray Blue'},
    {'symbol': 'TPU-SM151', 'hex': '#dac28f', 'name': 'Super Matte Satin Khaki Green'},
    {'symbol': 'TPU-SM154', 'hex': '#b8bbb5', 'name': 'Super Matte Battleship Gray'},
    {'symbol': 'TPU-SM155', 'hex': '#918f8b', 'name': 'Super Matte Quiet Night Gray'},
    {'symbol': 'TPU-SM156', 'hex': null, 'name': 'Super Matte Liquid Metal Silver'},
    {'symbol': 'TPU-SM157', 'hex': '#822436', 'name': 'Super Matte Liquid Metal Dragon Blood Red'},
    {'symbol': 'TPU-SM158', 'hex': '#840d2e', 'name': 'Super Matte Romani Red'},
    {'symbol': 'TPU-SM159', 'hex': '#4e4d52', 'name': 'Super Matte Electroplated Tungsten Steel'},
    {'symbol': 'TPU-SM160', 'hex': '#6a6c6d', 'name': 'Super Matte Frosted Dark Silver'},
    {'symbol': 'TPU-SM161', 'hex': '#d7bcb8', 'name': 'Super Satin Rose Gold T-Shirt'},
    {'symbol': 'TPU-SM162', 'hex': '#d4d88c', 'name': 'Super Matte Satin Princess Red'},
    {'symbol': 'TPU-SM163', 'hex': '#57807f', 'name': 'Super Matte Metallic Venom Green'},
    {'symbol': 'TPU-SM164', 'hex': '#42434a', 'name': 'Super Matte Lead Gray'},
    {'symbol': 'TPU-SM165', 'hex': '#00cbf2', 'name': 'Super Matte Tunisian Blue'},
    {'symbol': 'TPU-SM17', 'hex': '#bec6bc', 'name': 'Super Matte Magic Green Grey'},
    {'symbol': 'TPU-SM170', 'hex': '#741d2f', 'name': 'Super Matte Magic Flame Ruby'},
    {'symbol': 'TPU-SM171', 'hex': '#c7b5b2', 'name': 'Super Matte Metallic Satin Shangeyan'},
    {'symbol': 'TPU-SM172', 'hex': '#2c2d31', 'name': 'Super Satin Competition Blue'},
    {'symbol': 'TPU-SM175', 'hex': null, 'name': 'Super Matte Liquid Metallic Interstellar Silver'},
    {'symbol': 'TPU-SM176', 'hex': '#28646b', 'name': 'Super Matte Liquid Metal Tungsten Steel'},
    {'symbol': 'TPU-SM177', 'hex': '#bab2a7', 'name': 'Super Matte Metallic Liquid Metallic Bronze'},
    {'symbol': 'TPU-SM178', 'hex': '#e0e9ed', 'name': 'Super Liquid Metallic Somato Blue'},
    {'symbol': 'TPU-SM179', 'hex': '#f0efeb', 'name': 'Super Matt Liquid Metallic Crescent White'},
    {'symbol': 'TPU-SM180', 'hex': '#e7d6ce', 'name': 'Super Matte Liquid Metallic Shell Pink'},
    {'symbol': 'TPU-SM181', 'hex': '#ebedee', 'name': 'Super Matte Liquid Super Silver (Lamborghini)'},
    {'symbol': 'TPU-SM182', 'hex': '#675a4a', 'name': 'Super Matte Metallic Liquid Shadow Gold (Lamborghini)'},
    {'symbol': 'TPU-SM183', 'hex': '#c5bfba', 'name': 'Super Matte Metallic Liquid Metallic Titanium'},
    {'symbol': 'TPU-SM184', 'hex': '#0057b5', 'name': 'Super Liquid Metallic Azure Blue'},
    {'symbol': 'TPU-SM185', 'hex': '#868273', 'name': 'Super Matte Liquid Metallic Combat Green'},
    {'symbol': 'TPU-SM186', 'hex': '#6b7783', 'name': 'Super Matte Liquid Metal Gunmetal Gray'},
    {'symbol': 'TPU-SM203', 'hex': '#7aa194', 'name': 'Super Matte Olive Green Metallic'},
    {'symbol': 'TPU-SM28', 'hex': '#58736c', 'name': 'Super Matte Metallic Dark Green'},
    {'symbol': 'TPU-SM281', 'hex': '#798489', 'name': 'Super Matte Metallic Mystic Green'},
    {'symbol': 'TPU-SM30', 'hex': '#3d4452', 'name': 'Super Matte Black Fantasy Blue'},
    {'symbol': 'TPU-SM303', 'hex': '#cacdca', 'name': 'Super Matte Blue Charm Gold'},
    {'symbol': 'TPU-SM304', 'hex': '#b3bdca', 'name': 'Super Matte Capri Gray Purple'},
    {'symbol': 'TPU-SM32', 'hex': '#c4ae8f', 'name': 'Super Matte Satin Army Green'},
    {'symbol': 'TPU-SM390', 'hex': '#875d8d', 'name': 'Super Midnight Purple'},
    {'symbol': 'TPU-SM410', 'hex': '#555557', 'name': 'Super Matte Invisible Black'},
    {'symbol': 'TPU-SM411', 'hex': '#efeee7', 'name': 'Super Matte Twilight Gold'},
    {'symbol': 'TPU-SM412', 'hex': '#998867', 'name': 'Super Matte Metallic Golden Green'},
    {'symbol': 'TPU-SM413', 'hex': '#d0cd73', 'name': 'Super Matte Military Green (Lamborghini)'},
    {'symbol': 'TPU-SM414', 'hex': '#f1d4b0', 'name': 'Super Matt Desert Yellow'},
    {'symbol': 'TPU-SM415', 'hex': '#e0f6c6', 'name': 'Super Matte Metallic Track Gold Green (Lamborghini)'},
    {'symbol': 'TPU-SM416', 'hex': '#746367', 'name': 'Super Matte Metallic Flame Shadow Brown (Lamborghini)'},
    {'symbol': 'TPU-SM417', 'hex': '#323234', 'name': 'Super Matte Shadow Knight Gray (Lamborghini)'},
    {'symbol': 'TPU-SM418', 'hex': '#fecb00', 'name': 'Super Matt Racing Yellow'},
    {'symbol': 'TPU-SM419', 'hex': '#ffba78', 'name': 'Super Matt Sparkling Orange'},
    {'symbol': 'TPU-SM420', 'hex': '#a1b0c0', 'name': 'Super Matte Metallic Deep Gray'},
    {'symbol': 'TPU-SM421', 'hex': '#599493', 'name': 'Super Matte Magic Flame Brazilian Green'},
    {'symbol': 'TPU-SM422', 'hex': '#becce7', 'name': 'Super Matte Purple Mist Silver'},
    {'symbol': 'TPU-SM423', 'hex': '#a8aaac', 'name': 'Super Matte Extreme Gray'},
    {'symbol': 'TPU-SM424', 'hex': '#fadeb8', 'name': 'Super Matt AMG Desert Yellow'},
    {'symbol': 'TPU-SM425', 'hex': '#969189', 'name': 'Super Matte Shark Gray'},
    {'symbol': 'TPU-SM426', 'hex': '#87817e', 'name': 'Super Matte Steel Gray'},
    {'symbol': 'TPU-SM427', 'hex': '#8a8f89', 'name': 'Super Matte Metallic Titanium'},
    {'symbol': 'TPU-SM428', 'hex': '#eceae4', 'name': 'Super Matte White'},
    {'symbol': 'TPU-SM429', 'hex': '#474359', 'name': 'Super Matte Midnight Purple'},
    {'symbol': 'TPU-SM81', 'hex': '#676a69', 'name': 'Super Matte AMG Mountain Gray'},
    {'symbol': 'TPU-SM85', 'hex': '#947387', 'name': 'Super Matte Black Phantom Purple'},
    {'symbol': 'TPU-SM96', 'hex': '#3b3b3d', 'name': 'Super Matte Gunmetal Gray'},
    {'symbol': 'TPU-W010', 'hex': '#dbd7d1', 'name': 'Shell White'},
    {'symbol': 'TPU-W011', 'hex': '#ddd8d0', 'name': 'Pearl White'},
    {'symbol': 'TPU-W020', 'hex': '#dcd9ce', 'name': 'White to Gold'},
    {'symbol': 'TPU-W030', 'hex': '#e2dcd5', 'name': 'White to Red'},
    {'symbol': 'TPU-W040', 'hex': '#dcd7cf', 'name': 'White to Purple'},
    {'symbol': 'TPU-W050', 'hex': '#dbd5ce', 'name': 'White Blue'},
    {'symbol': 'TPU-WS010', 'hex': '#d9d3cc', 'name': 'Ceramic White'},
    {'symbol': 'TPU-WS011', 'hex': '#d7d3ce', 'name': 'Satin Ceramic White T'},
    {'symbol': 'TPU-X01', 'hex': '#f8f2ef', 'name': 'Floral Pink'},
  ];
}
